import React, { useEffect, useState } from 'react';

export default function MigrationReport({ metrics }) {
  const [isVisible, setIsVisible] = useState(false);

  // When metrics load, wait 2000ms for the "typing stream" in ExecutionPanel to finish 
  // before majestically fading the report onto the screen.
  useEffect(() => {
    if (metrics) {
      const timer = setTimeout(() => setIsVisible(true), 1500);
      return () => clearTimeout(timer);
    } else {
      setIsVisible(false);
    }
  }, [metrics]);

  if (!metrics) return null;

  return (
    <section 
      id="report" 
      className={`transition-all duration-1000 ease-out transform ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}
    >
      <div className="flex items-center gap-3 mb-6 mt-12 px-2">
        <h2 className="text-xl font-bold text-gray-100 tracking-wide uppercase drop-shadow-[0_0_10px_rgba(255,107,26,0.3)]">
          <span className="text-orange-500">4.</span> Migration Verdict & Analytics
        </h2>
        <span className="text-[9px] tracking-widest text-green-400 border border-green-500/30 bg-green-500/10 px-2 py-0.5 rounded-sm">
          GENERATED BY DYNAMODB
        </span>
      </div>

      <div className="report-grid">
        
        {/* QUALITY CARD */}
        <div className="report-card" style={{ transitionDelay: '0ms' }}>
          <div className="rc-label">RESPONSE QUALITY SCORE</div>
          <div className="rc-val" style={{color: "var(--green)"}}>{metrics.qualityScore}</div>
          <div className="rc-sub">out of 100 — LLM-as-judge evaluation</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA Equivalent</span><span style={{color: "var(--green)"}}>{metrics.qualityScore}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: `${metrics.qualityScore}%`, background: "var(--green)"}}></div>
            </div>
            <div className="rc-bar-label" style={{marginTop: ".6rem"}}><span>Source Model</span><span style={{color: "#a855f7"}}>{metrics.sourceQuality}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: `${metrics.sourceQuality}%`, background: "#a855f7"}}></div>
            </div>
          </div>
        </div>

        {/* LATENCY CARD */}
        <div className="report-card" style={{ transitionDelay: '150ms' }}>
          <div className="rc-label">LATENCY COMPARISON</div>
          <div className="rc-val" style={{color: "var(--cyan)"}}>{metrics.latencyDiff}</div>
          <div className="rc-sub">NVIDIA is faster on this workload</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA · p50</span><span style={{color: "var(--cyan)"}}>{metrics.targetLatency}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: "55%", background: "var(--cyan)"}}></div>
            </div>
            <div className="rc-bar-label" style={{marginTop: ".6rem"}}><span>Source · p50</span><span style={{color: "#a855f7"}}>{metrics.sourceLatency}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: "72%", background: "#a855f7"}}></div>
            </div>
          </div>
        </div>

        {/* TOKENS CARD */}
        <div className="report-card" style={{ transitionDelay: '300ms' }}>
          <div className="rc-label">TOKEN USAGE EFFICIENCY</div>
          <div className="rc-val" style={{color: "var(--orange)"}}>{metrics.tokenDiff}</div>
          <div className="rc-sub">NVIDIA consumes fewer output tokens</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>Output tokens (NVIDIA)</span><span style={{color: "var(--orange)"}}>{metrics.targetTokens}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: "62%", background: "var(--orange)"}}></div>
            </div>
            <div className="rc-bar-label" style={{marginTop: ".6rem"}}><span>Output tokens (Source)</span><span style={{color: "#a855f7"}}>{metrics.sourceTokens}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: "76%", background: "#a855f7"}}></div>
            </div>
          </div>
        </div>

        {/* COST CARD */}
        <div className="report-card" style={{ transitionDelay: '450ms' }}>
          <div className="rc-label">ESTIMATED MONTHLY SAVINGS</div>
          <div className="rc-val" style={{color: "var(--aws)"}}>{metrics.savingsAmount}</div>
          <div className="rc-sub">based on current API call volume (1M req/mo)</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA NIMs</span><span style={{color: "var(--aws)"}}>{metrics.targetCost}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{width: "58%", background: "var(--aws)"}}></div>
            </div>
            <div className="rc-bar-label" style={{marginTop: ".6rem"}}><span>Current Model</span><span style={{color: "#a855f7"}}>{metrics.sourceCost}</span></div>
            <div className="rc-bar">
               <div className="rc-bar-fill" style={{width: "100%", background: "#a855f7"}}></div>
            </div>
          </div>
        </div>

        {/* VERDICT CARD */}
        <div className="report-card full" style={{ transitionDelay: '600ms' }}>
          <div>
            <div className="rc-label">MIGRATION VERDICT</div>
            <div className="rc-val" style={{color: "var(--green)", fontSize: "2rem"}}>{metrics.verdict}</div>
            <div className="rc-sub">All quality thresholds met. NVIDIA outperforms source on fundamental KPIs.</div>
            <div className="verdict-badge bg-green-500/10 border border-green-500 text-green-400 mt-4 px-3 py-1 font-mono text-xs inline-block shadow-[0_0_10px_rgba(34,211,160,0.3)]">
              ✓ CONFIDENCE SCORE: {metrics.confidence} — PREPARE FOR DEPLOYMENT
            </div>
          </div>
          <div>
            <div style={{fontSize: ".7rem", color: "var(--muted)", lineHeight: "2", marginTop: "1rem"}}>
              <div style={{display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0"}}>
                <span>Structural correctness</span><span style={{color: "var(--green)"}}>PASS</span></div>
              <div style={{display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0"}}>
                <span>JSON schema validation</span><span style={{color: "var(--green)"}}>PASS</span></div>
              <div style={{display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0"}}>
                <span>Function calling compat.</span><span style={{color: "var(--green)"}}>PASS</span></div>
              <div style={{display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0"}}>
                <span>Semantic similarity</span><span style={{color: "var(--green)"}}>98.4%</span></div>
              <div style={{display: "flex", justifyContent: "space-between", padding: ".4rem 0"}}><span>Cost delta</span><span style={{color: "var(--green)"}}>{metrics.tokenDiff}</span></div>
            </div>
          </div>
        </div>

      </div>
    </section>
  );
}
