import React, { useEffect, useState } from 'react';
import html2canvas from 'html2canvas';
import jsPDF from 'jspdf';
import PDFReportTemplate from './PDFReportTemplate';

export default function MigrationReport({ metrics, sourceModel, targetModel }) {
  const [isVisible, setIsVisible] = useState(false);
  const [isExporting, setIsExporting] = useState(false);

  const exportPDF = async () => {
    const reportElement = document.getElementById('pdf-report-template');
    if (!reportElement) return;
    
    setIsExporting(true);
    // Bring into view slightly to ensure html2canvas can render reliably
    reportElement.style.top = '0px';
    try {
      const canvas = await html2canvas(reportElement, {
        backgroundColor: '#ffffff',
        scale: 2,
        logging: false
      });
      
      const imgData = canvas.toDataURL('image/png');
      const pdf = new jsPDF({
        orientation: 'p',
        unit: 'mm',
        format: 'a4'
      });
      
      const pdfWidth = pdf.internal.pageSize.getWidth();
      const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
      
      pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
      pdf.save(`Migration_Report_${sourceModel}_to_${targetModel}.pdf`);
    } catch (e) {
      console.error(e);
    } finally {
      reportElement.style.top = '-9999px';
      setIsExporting(false);
    }
  };
  // When metrics load, wait 2000ms for the "typing stream" in ExecutionPanel to finish 
  // before majestically fading the report onto the screen.
  useEffect(() => {
    if (metrics) {
      const timer = setTimeout(() => setIsVisible(true), 1500);
      return () => clearTimeout(timer);
    } else {
      setIsVisible(false);
    }
  }, [metrics]);

  if (!metrics) return null;

  return (
    <section
      id="report"
      className={`transition-all duration-1000 ease-out transform ${isVisible ? 'opacity-100 translate-y-0' : 'opacity-0 translate-y-10'}`}
    >
      <div className="flex items-center justify-between mb-6 mt-12 px-2">
        <div className="flex items-center gap-3">
          <h2 className="text-xl font-bold text-gray-100 tracking-wide uppercase drop-shadow-[0_0_10px_rgba(255,107,26,0.3)]">
            <span className="text-orange-500">4.</span> Migration Verdict & Analytics
          </h2>
          <span className="text-[9px] tracking-widest text-green-400 border border-green-500/30 bg-green-500/10 px-2 py-0.5 rounded-sm">
            GENERATED BY DYNAMODB
          </span>
        </div>
        
        <button 
          onClick={exportPDF}
          disabled={isExporting}
          className="bg-gray-800 hover:bg-gray-700 text-gray-300 text-[10px] uppercase tracking-wider px-3 py-1.5 rounded flex items-center gap-2 transition-colors disabled:opacity-50 border border-gray-600 shadow-lg"
          title="Download report as PDF"
        >
          {isExporting ? "Exporting..." : "⬇ Export PDF"}
        </button>
      </div>

      <div className="report-grid">

        {/* QUALITY CARD */}
        <div className="report-card" style={{ transitionDelay: '0ms' }}>
          <div className="rc-label">RESPONSE QUALITY SCORE</div>
          <div className="rc-val" style={{ color: "var(--green)" }}>{metrics.qualityScore}</div>
          <div className="rc-sub">out of 100 — LLM-as-judge evaluation</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA Equivalent</span><span style={{ color: "var(--green)" }}>{metrics.qualityScore}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: `${metrics.qualityScore}%`, background: "var(--green)" }}></div>
            </div>
            <div className="rc-bar-label" style={{ marginTop: ".6rem" }}><span>Source Model</span><span style={{ color: "#a855f7" }}>{metrics.sourceQuality}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: `${metrics.sourceQuality}%`, background: "#a855f7" }}></div>
            </div>
          </div>
        </div>

        {/* LATENCY CARD */}
        <div className="report-card" style={{ transitionDelay: '150ms' }}>
          <div className="rc-label">LATENCY COMPARISON</div>
          <div className="rc-val" style={{ color: "var(--cyan)" }}>{metrics.latencyDiff}</div>
          <div className="rc-sub">NVIDIA is faster on this workload</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA · p50</span><span style={{ color: "var(--cyan)" }}>{metrics.targetLatency}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "55%", background: "var(--cyan)" }}></div>
            </div>
            <div className="rc-bar-label" style={{ marginTop: ".6rem" }}><span>Source · p50</span><span style={{ color: "#a855f7" }}>{metrics.sourceLatency}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "72%", background: "#a855f7" }}></div>
            </div>
          </div>
        </div>

        {/* TOKENS CARD */}
        <div className="report-card" style={{ transitionDelay: '300ms' }}>
          <div className="rc-label">TOKEN USAGE EFFICIENCY</div>
          <div className="rc-val" style={{ color: "var(--orange)" }}>{metrics.tokenDiff}</div>
          <div className="rc-sub">NVIDIA consumes fewer output tokens</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>Output tokens (NVIDIA)</span><span style={{ color: "var(--orange)" }}>{metrics.targetTokens}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "62%", background: "var(--orange)" }}></div>
            </div>
            <div className="rc-bar-label" style={{ marginTop: ".6rem" }}><span>Output tokens (Source)</span><span style={{ color: "#a855f7" }}>{metrics.sourceTokens}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "76%", background: "#a855f7" }}></div>
            </div>
          </div>
        </div>

        {/* COST CARD */}
        <div className="report-card" style={{ transitionDelay: '450ms' }}>
          <div className="rc-label">ESTIMATED MONTHLY SAVINGS</div>
          <div className="rc-val" style={{ color: "var(--aws)" }}>{metrics.savingsAmount}</div>
          <div className="rc-sub">based on current API call volume (1M req/mo)</div>
          <div className="rc-bar-wrap">
            <div className="rc-bar-label"><span>NVIDIA NIMs</span><span style={{ color: "var(--aws)" }}>{metrics.targetCost}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "58%", background: "var(--aws)" }}></div>
            </div>
            <div className="rc-bar-label" style={{ marginTop: ".6rem" }}><span>Current Model</span><span style={{ color: "#a855f7" }}>{metrics.sourceCost}</span></div>
            <div className="rc-bar">
              <div className="rc-bar-fill" style={{ width: "100%", background: "#a855f7" }}></div>
            </div>
          </div>
        </div>

        {/* VERDICT CARD */}
        <div className="report-card full visible-card" style={{ transitionDelay: '600ms' }}>
          <div>
            <div className="rc-label">MIGRATION VERDICT</div>
            <div className="rc-val" style={{ color: metrics.verdict === "SAFE TO MIGRATE" ? "var(--green)" : metrics.verdict === "PROCEED WITH CAUTION" ? "var(--orange)" : "#f87171", fontSize: "2rem" }}>{metrics.verdict}</div>
            <div className="rc-sub">Score based on quality, semantic similarity, latency, and cost.</div>
            <div className={`verdict-badge mt-4 px-3 py-1 font-mono text-xs inline-block shadow-lg ${metrics.verdict === "SAFE TO MIGRATE" ? "bg-green-500/10 border border-green-500 text-green-400 shadow-[0_0_10px_rgba(34,211,160,0.3)]" : metrics.verdict === "PROCEED WITH CAUTION" ? "bg-orange-500/10 border border-orange-500 text-orange-400 shadow-[0_0_10px_rgba(249,115,22,0.3)]" : "bg-red-500/10 border border-red-500 text-red-400 shadow-[0_0_10px_rgba(248,113,113,0.3)]"}`}>
              {metrics.verdict === "SAFE TO MIGRATE" ? "✓" : "!"} OVERALL SCORE: {metrics.confidence} — {metrics.verdict === "SAFE TO MIGRATE" ? "READY FOR DEPLOYMENT" : "REVIEW RISKS"}
            </div>
          </div>
          <div>
            <div style={{ fontSize: ".7rem", color: "var(--muted)", lineHeight: "2", marginTop: "1rem" }}>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0" }}>
                <span>Structural correctness</span><span style={{ color: "var(--green)" }}>PASS</span></div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0" }}>
                <span>JSON schema validation</span><span style={{ color: "var(--green)" }}>PASS</span></div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0" }}>
                <span>Function calling compat.</span><span style={{ color: "var(--green)" }}>PASS</span></div>
              <div style={{ display: "flex", justifyContent: "space-between", borderBottom: "1px solid var(--border)", padding: ".4rem 0" }}>
                <span>Semantic similarity</span><span style={{ color: "var(--green)" }}>{metrics.semanticScore || "98.4%"}</span></div>
              <div style={{ display: "flex", justifyContent: "space-between", padding: ".4rem 0" }}><span>Cost delta</span><span style={{ color: "var(--green)" }}>{metrics.tokenDiff}</span></div>
            </div>
          </div>
        </div>

        {/* VERDICT DETAILS CARD */}
        {(metrics.strengths?.length > 0 || metrics.risks?.length > 0) && (
          <div className="report-card full visible-card" style={{ transitionDelay: '750ms', gridColumn: "1 / -1", display: 'flex', flexDirection: 'column', gap: '1rem' }}>
            <div className="rc-label" style={{ marginBottom: "0.5rem" }}>MIGRATION ANALYSIS DETAILS</div>
            <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '2rem' }}>
              <div>
                <h4 style={{ color: "var(--green)", fontSize: "0.8rem", fontWeight: "bold", marginBottom: "0.5rem", letterSpacing: "1px" }}>STRENGTHS ({metrics.strengths?.length || 0})</h4>
                <ul style={{ listStyleType: "disc", paddingLeft: "1.2rem", fontSize: "0.8rem", color: "var(--text-light)" }}>
                  {metrics.strengths?.map((s, i) => <li key={i} style={{ marginBottom: "0.3rem" }}>{s}</li>)}
                </ul>
              </div>
              <div>
                <h4 style={{ color: "var(--orange)", fontSize: "0.8rem", fontWeight: "bold", marginBottom: "0.5rem", letterSpacing: "1px" }}>RISKS & RECOMMENDATIONS</h4>
                <ul style={{ listStyleType: "disc", paddingLeft: "1.2rem", fontSize: "0.8rem", color: "var(--text-light)" }}>
                  {metrics.risks?.map((r, i) => <li key={`risk-${i}`} style={{ marginBottom: "0.3rem", color: "#f87171" }}>Risk: {r}</li>)}
                  {metrics.recommendations?.map((r, i) => <li key={`rec-${i}`} style={{ marginBottom: "0.3rem", color: "var(--cyan)" }}>Rec: {r}</li>)}
                </ul>
              </div>
            </div>
          </div>
        )}

      </div>
      <PDFReportTemplate metrics={metrics} sourceModel={sourceModel} targetModel={targetModel} />
    </section>
  );
}
